In [105]:
import pandas as pd
import numpy as np
p1=pd.read_csv(r"/content/bank-full.csv",delimiter=";")
p1

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

In [ ]:
p1.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [ ]:
p1.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [53]:
p1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [ ]:
p1.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [63]:
p1.drop("default",axis=1,inplace=True)
p1

age  job  marital  education  balance  housing  loan  contact  day  \
0       58    4        1          2     2143        1     0        2    5   
1       44    9        2          1       29        1     0        2    5   
2       33    2        1          1        2        1     1        2    5   
3       47    1        1          3     1506        1     0        2    5   
4       33   11        2          3        1        0     0        2    5   
...    ...  ...      ...        ...      ...      ...   ...      ...  ...   
45206   51    9        1          2      825        0     0        0   17   
45207   71    5        0          0     1729        0     0        0   17   
45208   72    5        1          1     5715        0     0        0   17   
45209   57    1        1          1      668        0     0        1   17   
45210   37    2        1          1     2971        0     0        0   17   

       month  duration  campaign  pdays  previous  poutcome  y  
0          8       261         1     -1         0         3  0  
1          8       151         1     -1         0         3  0  
2          8        76         1     -1         0         3  0  
3          8        92         1     -1         0         3  0  
4          8       198         1     -1         0         3  0  
...      ...       ...       ...    ...       ...       ... ..  
45206      9       977         3     -1         0         3  1  
45207      9       456         2     -1         0         3  1  
45208      9      1127         5    184         3         2  1  
45209      9       508         4     -1         0         3  0  
45210      9       361         2    188        11         1  0  

[45211 rows x 16 columns]

In [65]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
l1=p1["job"]
l11=le.fit_transform(l1)
l11.reshape(-1,1)
p1["job"]=l11

l2=p1["marital"]
l22=le.fit_transform(l2)
l22.reshape(-1,1)
p1["marital"]=l22

l3=p1["education"]
l33=le.fit_transform(l3)
l33.reshape(-1,1)
p1["education"]=l33

l4=p1["housing"]
l44=le.fit_transform(l4)
l44.reshape(-1,1)
p1["housing"]=l44

l5=p1["loan"]
l55=le.fit_transform(l5)
l55.reshape(-1,1)
p1["loan"]=l55

l6=p1["contact"]
l66=le.fit_transform(l6)
l66.reshape(-1,1)
p1["contact"]=l66

l7=p1["month"]
l77=le.fit_transform(l7)
l77.reshape(-1,1)
p1["month"]=l77

l8=p1["poutcome"]
l88=le.fit_transform(l8)
l88.reshape(-1,1)
p1["poutcome"]=l88

l9=p1["y"]
l99=le.fit_transform(l9)
l99.reshape(-1,1)
p1["y"]=l99

p1

age  job  marital  education  balance  housing  loan  contact  day  \
0       58    4        1          2     2143        1     0        2    5   
1       44    9        2          1       29        1     0        2    5   
2       33    2        1          1        2        1     1        2    5   
3       47    1        1          3     1506        1     0        2    5   
4       33   11        2          3        1        0     0        2    5   
...    ...  ...      ...        ...      ...      ...   ...      ...  ...   
45206   51    9        1          2      825        0     0        0   17   
45207   71    5        0          0     1729        0     0        0   17   
45208   72    5        1          1     5715        0     0        0   17   
45209   57    1        1          1      668        0     0        1   17   
45210   37    2        1          1     2971        0     0        0   17   

       month  duration  campaign  pdays  previous  poutcome  y  
0          8       261         1     -1         0         3  0  
1          8       151         1     -1         0         3  0  
2          8        76         1     -1         0         3  0  
3          8        92         1     -1         0         3  0  
4          8       198         1     -1         0         3  0  
...      ...       ...       ...    ...       ...       ... ..  
45206      9       977         3     -1         0         3  1  
45207      9       456         2     -1         0         3  1  
45208      9      1127         5    184         3         2  1  
45209      9       508         4     -1         0         3  0  
45210      9       361         2    188        11         1  0  

[45211 rows x 16 columns]

In [68]:
p1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  int64
 2   marital    45211 non-null  int64
 3   education  45211 non-null  int64
 4   balance    45211 non-null  int64
 5   housing    45211 non-null  int64
 6   loan       45211 non-null  int64
 7   contact    45211 non-null  int64
 8   day        45211 non-null  int64
 9   month      45211 non-null  int64
 10  duration   45211 non-null  int64
 11  campaign   45211 non-null  int64
 12  pdays      45211 non-null  int64
 13  previous   45211 non-null  int64
 14  poutcome   45211 non-null  int64
 15  y          45211 non-null  int64
dtypes: int64(16)
memory usage: 5.5 MB


In [69]:
Y=p1["y"]
Y

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int64

In [70]:
X=p1.drop("y",axis=1)
X

age  job  marital  education  balance  housing  loan  contact  day  \
0       58    4        1          2     2143        1     0        2    5   
1       44    9        2          1       29        1     0        2    5   
2       33    2        1          1        2        1     1        2    5   
3       47    1        1          3     1506        1     0        2    5   
4       33   11        2          3        1        0     0        2    5   
...    ...  ...      ...        ...      ...      ...   ...      ...  ...   
45206   51    9        1          2      825        0     0        0   17   
45207   71    5        0          0     1729        0     0        0   17   
45208   72    5        1          1     5715        0     0        0   17   
45209   57    1        1          1      668        0     0        1   17   
45210   37    2        1          1     2971        0     0        0   17   

       month  duration  campaign  pdays  previous  poutcome  
0          8       261         1     -1         0         3  
1          8       151         1     -1         0         3  
2          8        76         1     -1         0         3  
3          8        92         1     -1         0         3  
4          8       198         1     -1         0         3  
...      ...       ...       ...    ...       ...       ...  
45206      9       977         3     -1         0         3  
45207      9       456         2     -1         0         3  
45208      9      1127         5    184         3         2  
45209      9       508         4     -1         0         3  
45210      9       361         2    188        11         1  

[45211 rows x 15 columns]

In [71]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(36168, 15)
(9043, 15)
(36168,)
(9043,)


In [143]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import r2_score
LR=LogisticRegression()
LR.fit(X_train,Y_train)
y_pred=LR.predict(X_test)
print(y_pred)
print(Y_test)
print('Mean Absolute Error: ', metrics.mean_absolute_error(Y_test,y_pred))
print('Hean Squared Error: ', metrics.mean_squared_error(Y_test,y_pred))
r2 = r2_score(Y_test, y_pred)
print(f"R2 Score: {r2}")

[0 0 0 ... 0 0 0]
28127    0
20256    0
6285     0
198      0
2417     0
        ..
11289    0
9162     0
25871    0
43183    1
34395    0
Name: y, Length: 9043, dtype: int64
Mean Absolute Error:  0.1127944266283313
Hean Squared Error:  0.1127944266283313
R2 Score: -0.09632054312905414


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [144]:
from sklearn.naive_bayes import GaussianNB
NB.fit(X_train,Y_train)
Ypred=NB.predict(X_test)
print(Y_test)
print(Ypred)
print('Mean Absolute Error: ', metrics.mean_absolute_error(Y_test,Ypred))
print('Hean Squared Error: ', metrics.mean_squared_error(Y_test,Ypred))
r2 = r2_score(Y_test, Ypred)
print(f"R2 Score: {r2}")

28127    0
20256    0
6285     0
198      0
2417     0
        ..
11289    0
9162     0
25871    0
43183    1
34395    0
Name: y, Length: 9043, dtype: int64
[0 0 0 ... 0 1 0]
Mean Absolute Error:  0.1578016145084596
Hean Squared Error:  0.1578016145084596
R2 Score: -0.5337739363187843


In [134]:
from sklearn.svm import SVC
SVCClassifier=SVC()
SVCClassifier.fit(X_train,Y_train)
YPred=SVCClassifier.predict(X_test)
print(Y_test)
print(YPred)
print('Mean Absolute Error: ', metrics.mean_absolute_error(Y_test,YPred))
print('Hean Squared Error: ', metrics.mean_squared_error(Y_test,YPred))
r2 = r2_score(Y_test, YPred)
print(f"R2 Score: {r2}")

28127    0
20256    0
6285     0
198      0
2417     0
        ..
11289    0
9162     0
25871    0
43183    1
34395    0
Name: y, Length: 9043, dtype: int64
[0 0 0 ... 0 0 0]
Mean Absolute Error:  0.11655424084927568
Hean Squared Error:  0.11655424084927568
R2 Score: -0.13286456123335588


In [141]:
from sklearn.tree import DecisionTreeClassifier
DTC= DecisionTreeClassifier()
DTC.fit(X_train,Y_train)
Y_Pred=DTC.predict(X_test)
print(Y_Pred)
print(Y_test)
print('Mean Absolute Error: ', metrics.mean_absolute_error(Y_test,Y_Pred))
print('Hean Squared Error: ', metrics.mean_squared_error(Y_test,Y_Pred))
r2 = r2_score(Y_test, Y_Pred)
print(f"R2 Score: {r2}")

[0 0 0 ... 0 0 1]
28127    0
20256    0
6285     0
198      0
2417     0
        ..
11289    0
9162     0
25871    0
43183    1
34395    0
Name: y, Length: 9043, dtype: int64
Mean Absolute Error:  0.12938184230896826
Hean Squared Error:  0.12938184230896826
R2 Score: -0.2575441524127384


In [140]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier()
RFC.fit(X_train,Y_train)
YPRed=RFC.predict(X_test)
print(YPRed)
print(Y_test)
print('Mean Absolute Error: ', metrics.mean_absolute_error(Y_test,YPRed))
print('Hean Squared Error: ', metrics.mean_squared_error(Y_test,YPRed))
r2 = r2_score(Y_test, YPRed)
print(f"R2 Score: {r2}")


[0 0 0 ... 0 0 0]
28127    0
20256    0
6285     0
198      0
2417     0
        ..
11289    0
9162     0
25871    0
43183    1
34395    0
Name: y, Length: 9043, dtype: int64
Mean Absolute Error:  0.09642817649010284
Hean Squared Error:  0.09642817649010284
R2 Score: 0.06275341803084789
